In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('consumer_complaints.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (5,11) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
data.head()

date_received           product  ... consumer_disputed? complaint_id
0    08/30/2013          Mortgage  ...                Yes     511074.0
1    08/30/2013          Mortgage  ...                Yes     511080.0
2    08/30/2013  Credit reporting  ...                 No     510473.0
3    08/30/2013      Student loan  ...                Yes     510326.0
4    08/30/2013   Debt collection  ...                Yes     511067.0

[5 rows x 18 columns]

In [4]:
data.shape

(383538, 18)

In [5]:
data.columns

Index(['date_received', 'product', 'sub_product', 'issue', 'sub_issue',
       'consumer_complaint_narrative', 'company_public_response', 'company',
       'state', 'zipcode', 'tags', 'consumer_consent_provided',
       'submitted_via', 'date_sent_to_company', 'company_response_to_consumer',
       'timely_response', 'consumer_disputed?', 'complaint_id'],
      dtype='object')

In [6]:
df=data[['consumer_complaint_narrative','product']]
df.head()

consumer_complaint_narrative           product
0                          NaN          Mortgage
1                          NaN          Mortgage
2                          NaN  Credit reporting
3                          NaN      Student loan
4                          NaN   Debt collection

In [7]:
df.isna().sum()

consumer_complaint_narrative    334222
product                              0
dtype: int64

In [8]:
df.dropna(inplace=True)
df.reset_index(drop=True,inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [9]:
df.shape

(49316, 2)

In [10]:
df.duplicated().value_counts()

False    48479
True       837
dtype: int64

In [11]:
df.drop_duplicates(inplace=True,ignore_index=True)
df.reset_index(drop=True,inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [12]:
df.shape

(48479, 2)

In [13]:
df['product'].value_counts()

Debt collection            13125
Mortgage                   11128
Credit reporting            8798
Credit card                 5632
Bank account or service     4044
Consumer Loan               2644
Student loan                1648
Payday loan                  543
Money transfers              499
Prepaid card                 341
Other financial service       77
Name: product, dtype: int64

In [14]:
df['product'].loc[(df['product'] == "Credit reporting") | (df['product'] == "Credit reporting, credit repair services, or other personal consumer reports") | 
         (df['product'] == "Credit card") | (df['product'] == "Credit card or prepaid card") | (df['product'] == "Prepaid card")] = "Credit Card Related"

df['product'].loc[(df['product'] == "Student loan") | (df['product'] == "Consumer Loan") | 
         (df['product'] == "Vehicle loan or lease") | (df['product'] == "Payday loan") | (df['product'] == "Payday loan, title loan, or personal loan")] = "Loan Related"

df['product'].loc[(df['product']== "Bank account or service") | (df['product'] == "Checking or savings account") | 
         (df['product'] == "Money transfer, virtual currency, or money service") | (df['product'] == "Money transfers")] = "Bank Services"

df['product'].loc[(df['product'] == "Debt collection") | (df['product']== "Mortgage") | 
         (df['product'] == "Virtual currency") | (df['product'] == "Other financial service") | (df['product'] == "Prepaid card")] = "Others Services"

df.reset_index(inplace = True)
df.drop('index',axis='columns', inplace=True)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is tr

In [15]:
df['product'].value_counts()

Others Services        24330
Credit Card Related    14771
Loan Related            4835
Bank Services           4543
Name: product, dtype: int64

In [16]:
df.shape

(48479, 2)

In [17]:
df.head()

consumer_complaint_narrative          product
0  XXXX has claimed I owe them {$27.00} for XXXX ...  Others Services
1  Due to inconsistencies in the amount owed that...     Loan Related
2  In XX/XX/XXXX my wages that I earned at my job...  Others Services
3  I have an open and current mortgage with Chase...  Others Services
4  XXXX was submitted XX/XX/XXXX. At the time I s...  Others Services

In [18]:
def example_complain(index):
    example = df[df.index == index][['consumer_complaint_narrative', 'product']].values[0]
    if len(example) > 0:
        print(example[0])
        print()
        print('Category:', example[1])

In [77]:
example_complain(8)

opened bank america credit card 1520 year ago interest account low time 7 year ago got notice interest changing going prime plus 2 thinkprime going back several bank option close account stay old term cond lock interest rate till paid offso new term cond acceptingi closed account made payment since time never latemy history show thisi month past 5 year plus schedule payment online ea month get conformation number payment scheduledon account done 5years got conformation number transaction payment due get call home rude man # caller id say calling card service payment late late charge meant term cond charged irs getting sent statementi thought scam tell owned bank america still nasty threaten 7days past duei got nasty eplained scheduled payment conformation # careafter 1hr plus haurasing hung called bank america customer service 65hrs later phone people get told internet dept saw scheduled payment said bank america wrong 100 know fi problemapparently time week put new billing system syst

In [20]:
import nltk
import re
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')
nltk.download('all')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]   

True

In [22]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

df = df.reset_index(drop=True)
REPLACE_BY_SPACE_RE = re.compile('[/(){}\[\]\|@,;]')
BAD_SYMBOLS_RE = re.compile('[^0-9a-z #+_]')

def clean_text(text):
    text = text.lower() # lowercase text
    text = REPLACE_BY_SPACE_RE.sub(' ', text) # replace REPLACE_BY_SPACE_RE symbols by space in text. substitute the matched string in REPLACE_BY_SPACE_RE with space.
    text = BAD_SYMBOLS_RE.sub('', text) # remove symbols which are in BAD_SYMBOLS_RE from text. substitute the matched string in BAD_SYMBOLS_RE with nothing. 
    text = text.replace('x', '') # replacing x woth nothing
    text = text.split() ## Splitting each word from sentence
    text = [lemmatizer.lemmatize(word) for word in text if not word in stopwords.words('english')] ## Removing stopwords and using lematization for dictionary words
    text = ' '.join(text) ## Again joining all words to form a sentence
    return text

df['consumer_complaint_narrative'] = df['consumer_complaint_narrative'].apply(clean_text)


In [23]:
example_complain(5)

eperian reporting open current mortgage loan bk reporting monthly payment eperian supressing information refuse accurately report payment show account open debt officially reinstated chapter bk chapter bk eperian legal right rport current status mortgage

Category: Others Services


In [24]:
df.head()

consumer_complaint_narrative          product
0  claimed owe 2700 year despite proof payment se...  Others Services
1  due inconsistency amount owed told bank amount...     Loan Related
2  wage earned job decreased almost half knew tro...  Others Services
3  open current mortgage chase bank # chase repor...  Others Services
4  submitted time submitted complaint dealt rushm...  Others Services

In [25]:
df.duplicated().value_counts()

False    48270
True       209
dtype: int64

In [26]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True,inplace=True)

In [27]:
df.shape

(48270, 2)

In [28]:
df.isna().sum()

consumer_complaint_narrative    0
product                         0
dtype: int64

In [29]:
# The maximum number of words to be used. (most frequent)
MAX_NB_WORDS = 50000
# Max number of words in each complaint.
MAX_SEQUENCE_LENGTH = 250
# This is fixed.
EMBEDDING_DIM = 100

In [30]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=MAX_NB_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~', lower=True)
tokenizer.fit_on_texts(df['consumer_complaint_narrative'].values)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 49535 unique tokens.


In [31]:
tokenizer

In [32]:
df['consumer_complaint_narrative'].values

array(['claimed owe 2700 year despite proof payment sent canceled check ownpaid invoice 2700 continue insist owe collection agency stop harassment bill already paid four year ago',
       'due inconsistency amount owed told bank amount reported credit reporting agency advised write good letter order address issue request negative entry removed credit report together vehicle stolen declared total loss insurance company insurance company gap insurancw companypaid outstanding balance loan told bank still balance due loan good faith without received proof still balance made partial payment towards remaining debt sent goodwill letter still offering pay remainder debt echange removal negative entry credit report one point 2015 per credit monitoring agency showed delinquent balance 000 checked credit report 2015 delinquent balance 140000 monies gap insurance insurance company paid bank say still owe 62000 21000 already paid contacted bank via return receipt mail given courtesy response yet',


In [33]:
word_index

{'credit': 1,
 'account': 2,
 'payment': 3,
 'loan': 4,
 'would': 5,
 'bank': 6,
 'time': 7,
 'debt': 8,
 'report': 9,
 'told': 10,
 'call': 11,
 'nt': 12,
 'mortgage': 13,
 'company': 14,
 'received': 15,
 'card': 16,
 'information': 17,
 'called': 18,
 'month': 19,
 'day': 20,
 'letter': 21,
 'year': 22,
 'pay': 23,
 'never': 24,
 'get': 25,
 'paid': 26,
 'sent': 27,
 'number': 28,
 'back': 29,
 'said': 30,
 'could': 31,
 'collection': 32,
 'phone': 33,
 'also': 34,
 'amount': 35,
 '2015': 36,
 'home': 37,
 'fee': 38,
 'money': 39,
 'due': 40,
 'made': 41,
 'service': 42,
 'since': 43,
 'asked': 44,
 'u': 45,
 'well': 46,
 'balance': 47,
 'charge': 48,
 'check': 49,
 'even': 50,
 'still': 51,
 'make': 52,
 'interest': 53,
 'one': 54,
 'date': 55,
 'late': 56,
 'agency': 57,
 'help': 58,
 'bill': 59,
 'reporting': 60,
 'name': 61,
 'contacted': 62,
 'statement': 63,
 'know': 64,
 'request': 65,
 'complaint': 66,
 'new': 67,
 'need': 68,
 'modification': 69,
 'issue': 70,
 'customer': 

In [34]:
X = tokenizer.texts_to_sequences(df['consumer_complaint_narrative'].values)

In [35]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences(X, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor:', X.shape)

Shape of data tensor: (48270, 250)


In [36]:
tokenizer.texts_to_sequences(df['consumer_complaint_narrative'].values)[0]

[596,
 126,
 3516,
 22,
 479,
 175,
 3,
 27,
 1146,
 49,
 22771,
 1117,
 3516,
 236,
 2073,
 126,
 32,
 57,
 208,
 821,
 59,
 193,
 26,
 1172,
 22,
 187]

In [37]:
X[0]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,

In [56]:
Y = pd.get_dummies(df['product']).values
print('Shape of label tensor:', Y.shape)

Shape of label tensor: (48270, 4)


In [73]:
df.head(12)

consumer_complaint_narrative              product
0   claimed owe 2700 year despite proof payment se...      Others Services
1   due inconsistency amount owed told bank amount...         Loan Related
2   wage earned job decreased almost half knew tro...      Others Services
3   open current mortgage chase bank # chase repor...      Others Services
4   submitted time submitted complaint dealt rushm...      Others Services
5   eperian reporting open current mortgage loan b...      Others Services
6   complaint well fargo bank violation term condi...      Others Services
7   spoke green tree representative 2014 annual es...      Others Services
8   opened bank america credit card 1520 year ago ...  Credit Card Related
9   applied loan purchased vehicle month 2014 told...         Loan Related
10  disappointed cfpb help resolve fraudulant loan...      Others Services
11  mel harris assoc used deceptive collection pra...  Credit Card Related

In [76]:
Y[11]

array([0, 1, 0, 0], dtype=uint8)

In [ ]:
## ['Bank Services','Credit Card Related','Loan Related','Others Services']

In [60]:
print('Shape of X : ',X.shape)
print('Shape of Y : ',Y.shape)

Shape of X :  (48270, 250)
Shape of Y :  (48270, 4)


In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(38616, 250) (38616, 4)
(9654, 250) (9654, 4)


## Model using RNN

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, SimpleRNN, SpatialDropout1D

In [ ]:
model = Sequential()
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(SimpleRNN(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 250, 100)          5000000   
                                                                 
 spatial_dropout1d (SpatialD  (None, 250, 100)         0         
 ropout1D)                                                       
                                                                 
 simple_rnn (SimpleRNN)      (None, 100)               20100     
                                                                 
 dense (Dense)               (None, 4)                 404       
                                                                 
Total params: 5,020,504
Trainable params: 5,020,504
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
### Finally Training
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=5,batch_size=64)

Epoch 1/5
818/818 [==============================] - 183s 221ms/step - loss: 1.0531 - accuracy: 0.5555 - val_loss: 1.0096 - val_accuracy: 0.5723
Epoch 2/5
818/818 [==============================] - 181s 222ms/step - loss: 0.8706 - accuracy: 0.6634 - val_loss: 0.7633 - val_accuracy: 0.7329
Epoch 3/5
818/818 [==============================] - 181s 222ms/step - loss: 0.8324 - accuracy: 0.6867 - val_loss: 0.8850 - val_accuracy: 0.6931
Epoch 4/5
818/818 [==============================] - 185s 227ms/step - loss: 0.9367 - accuracy: 0.6238 - val_loss: 0.8269 - val_accuracy: 0.6975
Epoch 5/5
818/818 [==============================] - 181s 222ms/step - loss: 0.9157 - accuracy: 0.6423 - val_loss: 0.9870 - val_accuracy: 0.6236


In [ ]:
model.evaluate(X_test,Y_test)

409/409 [==============================] - 9s 21ms/step - loss: 0.9870 - accuracy: 0.6236


[0.987004816532135, 0.6235662698745728]

## Model using LSTM

In [78]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D

In [79]:
X.shape[1]

250

In [80]:
model = Sequential()
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 250, 100)          5000000   
                                                                 
 spatial_dropout1d_3 (Spatia  (None, 250, 100)         0         
 lDropout1D)                                                     
                                                                 
 lstm_3 (LSTM)               (None, 100)               80400     
                                                                 
 dense_3 (Dense)             (None, 4)                 404       
                                                                 
Total params: 5,080,804
Trainable params: 5,080,804
Non-trainable params: 0
_________________________________________________________________
None


In [81]:
### Finally Training
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=5,batch_size=64)

Epoch 1/5
604/604 [==============================] - 484s 797ms/step - loss: 0.6804 - accuracy: 0.7553 - val_loss: 0.5793 - val_accuracy: 0.7990
Epoch 2/5
604/604 [==============================] - 480s 794ms/step - loss: 0.4559 - accuracy: 0.8537 - val_loss: 0.4931 - val_accuracy: 0.8472
Epoch 3/5
604/604 [==============================] - 484s 801ms/step - loss: 0.3693 - accuracy: 0.8845 - val_loss: 0.4517 - val_accuracy: 0.8498
Epoch 4/5
604/604 [==============================] - 481s 797ms/step - loss: 0.3213 - accuracy: 0.8989 - val_loss: 0.5979 - val_accuracy: 0.8231
Epoch 5/5
604/604 [==============================] - 483s 799ms/step - loss: 0.3105 - accuracy: 0.9007 - val_loss: 0.7200 - val_accuracy: 0.7798


In [82]:
model.evaluate(X_test,Y_test)

302/302 [==============================] - 22s 72ms/step - loss: 0.7200 - accuracy: 0.7798


[0.7199808955192566, 0.779780387878418]

In [83]:
y_pred=np.argmax(model.predict(X_test),axis=1)
y_pred

array([1, 3, 1, ..., 3, 1, 2])

In [84]:
y_pred[1]

3

In [85]:
new_complaint = ['I am a victim of identity theft and someone stole my identity and personal information to open up a Visa credit card account with Bank of America. The following Bank of America Visa credit card account do not belong to me : XXXX.']
seq = tokenizer.texts_to_sequences(new_complaint)
padded = pad_sequences(seq, maxlen=MAX_SEQUENCE_LENGTH)
pred = model.predict(padded)
labels = ['Bank Services','Credit Card Related','Loan Related','Others Services']
print(pred, labels[np.argmax(pred)])

[[0.08778185 0.84107107 0.00523186 0.06591524]] Credit Card Related


In [86]:
# This should give 'Other Services'

new_complaint = ['I am very disappointed that the CFPB did not help to resolve this fraudulant loan. # XXXX between XXXX XXXX and XXXX, FF ( AKA ) One West. Case # XXXX with CFPB.']
seq = tokenizer.texts_to_sequences(new_complaint)
padded = pad_sequences(seq, maxlen=MAX_SEQUENCE_LENGTH)
pred = model.predict(padded)
labels = ['Bank Services','Credit Card Related','Loan Related','Others Services']
print(pred, labels[np.argmax(pred)])

[[0.00631927 0.00500769 0.02745851 0.96121454]] Others Services


In [88]:
# This should give 'Credit Card Related'

new_complaint = ['opened bank america credit card 1520 year ago interest account low time 7 year ago got notice interest changing going prime plus 2 thinkprime going back several bank option close account stay old term cond lock interest rate till paid offso new term cond acceptingi closed account made payment since time never latemy history show thisi month past 5 year plus schedule payment online ea month get conformation number payment scheduledon account done 5years got conformation number transaction payment due get call home rude man # caller id say calling card service payment late late charge meant term cond charged irs getting sent statementi thought scam tell owned bank america still nasty threaten 7days past duei got nasty eplained scheduled payment conformation # careafter 1hr plus haurasing hung called bank america customer service 65hrs later phone people get told internet dept saw scheduled payment said bank america wrong 100 know fi problemapparently time week put new billing system system update took account put un active position payment scheduled could find account apply paymenti made yet new system could apply paymenti way knowing find account way ask fi issue idea fi problem people installed new updated system input account could seeni suppose get call someone corp level net day address problem never happened spend another 5 hour phone way phone going call home phone put hold speak supervisor 2hrs later never happened called cell phone got supervisor nothing 3 hoursi asked 1thing never got asked 2500 credit late fee refused kept reading note put hold come back nothing tried eplain needed done would listen 3 hour 12 hour getting filling complaint also concern nothave spoken attorney yet believe right violated get call threaten spoke told az internet dept bank america fault needed fi told payment late fee refuse service refuse wave fee faulti conformation # payment always made time never late yet getting called home threaten bank america wrong paying nowthis wrong really feel violated wayi also found supervisor spoke never recorded ever spoke call center scarolinaand call never never put note spoke get right allthank time']
seq = tokenizer.texts_to_sequences(new_complaint)
padded = pad_sequences(seq, maxlen=MAX_SEQUENCE_LENGTH)
pred = model.predict(padded)
labels = ['Bank Services','Credit Card Related','Loan Related','Others Services']
print(pred, labels[np.argmax(pred)])

[[0.12367404 0.7201883  0.02600319 0.13013451]] Credit Card Related
